# Generated by Django 5.0.6 on 2024-07-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_item_nameextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collegename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementaryname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secondaryname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vocationalname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
