# Generated by Django 5.0.6 on 2024-07-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item_collegename_item_elementaryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='telphone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
